### PR TITLE
Add missing awesome dev!

### PR DESCRIPTION
**Pull request by achasveachas**
The awesomest of devs was missing apparently!

### CODE REVIEW

**Comment by bvlktech** [comment]
> The awesomest of devs was missing apparently!

Haha I would but that would seem vainish and this is to show off other people i dont deserve to be on this list.

**Comment by achasveachas** [comment]
Meh, people coming here deserve to see your name too.

It isn't vain if you're not the one adding it... 😉

**Comment by bvlktech** [comment]
haha true but this is mostly to show off awesome people like you! not me im just here to help is all

**Comment by achasveachas** [comment]
Don't change the fact that you're awesome too...

**Comment by bvlktech** [comment]
i dont see myself as such i just see myself as a being in space here to help others no need to add me to any list im fine in the background letting others take the limelight

**Comment by achasveachas** [comment]
Stop being so humble and hit merge already 😜

**Comment by bvlktech** [comment]
Haha busy building an app this app almost done about to commit code => https://github.com/bvlktech/ElectronPass

**Pull request merged**
